server:
  port: 9999

jwt:
  secret: andicar
  expiration: 7200000
  token: Bearer

spring:
  redis:
    timeout: 1000
    database: 0
    host: localhost
    port: 6379
#    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
# 自定义404 出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false